//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string message { get; set; }
        public Nullable<bool> is_read { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
    //TODO: Principios utilizados: S - O - I
    // S: (Single Responsibility Principle)
    // Por qué? La clase Notifications representa únicamente la estructura de una notificación en el sistema,
    // sin incluir lógica adicional.
    // O: (Open/Closed Principle)
    // Por qué? Puede extenderse fácilmente para agregar nuevos campos o comportamientos sin modificar la clase base,
    // por ejemplo, agregando un método de marcado o categorías de notificación.
    // I: (Interface Segregation Principle)
    // Por qué? Podría implementar interfaces específicas como INotificationEntity,
    // enfocadas únicamente en los métodos que una notificación debe cumplir.
}
