//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
    //TODO: Principios utilizados: S - O - I
    // S: (Single Responsibility Principle)
    // Por qué? La clase Products tiene la única responsabilidad de representar la entidad "Producto",
    // con sus atributos y relaciones con otras tablas (Categorías, Inventario y Proveedores).
    // O: (Open/Closed Principle)
    // Por qué? Está abierta a extensión (por ejemplo, agregar propiedades o métodos de validación),
    // sin necesidad de modificar su definición base.
    // I: (Interface Segregation Principle)
    // Por qué? Puede implementar en el futuro interfaces específicas (como IProductEntity o IAuditable)
    // sin depender de métodos innecesarios que no correspondan al contexto de un producto.
}
